"""Public infrastructure facade."""

from .concurrency import ConcurrencyContractError, ReadWriteLock
from .config import (
    ConfigEnvironment,
    ConfigError,
    ConfigFileToml,
    ConfigSource,
    DotenvSource,
    ProjectConfig,
)
from .filesystem import (
    FilesystemBoundaryError,
    TextLineSliceRead,
    TextPrefixRead,
    atomic_copy_file,
    atomic_write_bytes,
    atomic_write_text,
    file_digest,
    read_text_line_slice,
    read_text_prefix,
    resolve_under_root,
)
from .dependencies import (
    DependencyCheck,
    DependencyChecker,
    DependencyContractError,
    DependencyDistribution,
    DependencyExecutable,
    DependencyError,
    DependencyRequirement,
)
from .json import (
    JsonObject,
    JsonScalar,
    JsonTypeError,
    JsonValue,
    dumps_json,
    to_json_object,
    to_json_value,
)
from .staging import (
    DEFAULT_STAGING_ROOT,
    StagingDirectoryManager,
    StagingError,
)
from .time import BusinessDay, BusinessDayError
from .continuation import (
    MIN_CONTINUATION_PAGE_CHARS,
    ContinuationError,
    ContinuationFailureReason,
    ContinuationPosition,
    OpaqueContinuationCodec,
    continue_json_sequence,
)
__all__ = [
    "ConcurrencyContractError",
    "ConfigEnvironment",
    "ConfigError",
    "ConfigFileToml",
    "ConfigSource",
    "ContinuationError",
    "ContinuationFailureReason",
    "ContinuationPosition",
    "DotenvSource",
    "DependencyCheck",
    "DependencyChecker",
    "DependencyContractError",
    "DependencyDistribution",
    "DependencyExecutable",
    "DependencyError",
    "DependencyRequirement",
    "DEFAULT_STAGING_ROOT",
    "FilesystemBoundaryError",
    "JsonObject",
    "JsonScalar",
    "JsonTypeError",
    "JsonValue",
    "MIN_CONTINUATION_PAGE_CHARS",
    "OpaqueContinuationCodec",
    "ProjectConfig",
    "ReadWriteLock",
    "StagingDirectoryManager",
    "StagingError",
    "TextLineSliceRead",
    "TextPrefixRead",
    "BusinessDay",
    "BusinessDayError",
    "atomic_copy_file",
    "atomic_write_bytes",
    "atomic_write_text",
    "continue_json_sequence",
    "dumps_json",
    "file_digest",
    "read_text_line_slice",
    "read_text_prefix",
    "resolve_under_root",
    "to_json_object",
    "to_json_value",
]
