"""Configuration module for TinySoul.

Provides centralized access to framework-wide settings.
"""

from .defaults import (
    DEFAULT_BASE_RETRY_DELAY,
    DEFAULT_CONTENT_TRUNCATE,
    DEFAULT_INTERPRETER_CLEANED_PREVIEW_CHARS,
    DEFAULT_INTERPRETER_RAW_PREVIEW_CHARS,
    DEFAULT_LLM_TIMEOUT,
    DEFAULT_LOG_CATEGORIES,
    DEFAULT_LOG_COLOR,
    DEFAULT_LOG_LEVEL,
    DEFAULT_LLM_PARSE_PREVIEW_CHARS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_TOKENS,
    DEFAULT_MAX_TURNS,
    DEFAULT_PROVIDER_MODEL_SPECS,
    DEFAULT_CHAT_PROFILES,
    DEFAULT_CHAT_PROVIDER_CHAIN,
    DEFAULT_REFERENCE_TRUNCATE,
    DEFAULT_SCRIPT_TIMEOUT,
    DEFAULT_TEMPERATURE,
)
from .settings import GlobalSettings, settings

__all__ = [
    "GlobalSettings",
    "settings",
    # Defaults (re-exported for discoverability)
    "DEFAULT_TEMPERATURE",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_BASE_RETRY_DELAY",
    "DEFAULT_PROVIDER_MODEL_SPECS",
    "DEFAULT_CHAT_PROVIDER_CHAIN",
    "DEFAULT_CHAT_PROFILES",
    "DEFAULT_REFERENCE_TRUNCATE",
    "DEFAULT_CONTENT_TRUNCATE",
    "DEFAULT_LLM_TIMEOUT",
    "DEFAULT_LLM_PARSE_PREVIEW_CHARS",
    "DEFAULT_INTERPRETER_RAW_PREVIEW_CHARS",
    "DEFAULT_INTERPRETER_CLEANED_PREVIEW_CHARS",
    "DEFAULT_SCRIPT_TIMEOUT",
    "DEFAULT_MAX_TURNS",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_LOG_CATEGORIES",
    "DEFAULT_LOG_COLOR",
]
