"""HTTP request schemas grouped by Endpoint protocol domain."""

from .configuration import (
    ConfigApplyRequest,
    ConfigDeleteMutationRequest,
    ConfigMutationRequest,
    ConfigPatchRequest,
    ConfigSetMutationRequest,
    PresetCreateRequest,
    PresetUpdateRequest,
)
from .reflection import ReflectionRequest
from .responses import (
    ActionCatalogResponse,
    CommandReceiptResponse,
    ConfigCatalogResponse,
    ConfigMutationResponse,
    ConfigResponse,
    ContextMessagesResponse,
    ContextOverviewResponse,
    HealthResponse,
    InteractionPageResponse,
    JobDetailResponse,
    JobListResponse,
    JobOutputResponse,
    PageResponse,
    PresetDeleteResponse,
    PresetListResponse,
    PresetResponse,
    ResourceResolveResponse,
    RuntimeStatusResponse,
    SearchResponse,
    TurnResponse,
    TurnListResponse,
)
from .runtime import ControlRequest, InputRequest
from .turns import (
    TurnCreateRequest,
    TurnGrantRequest,
    TurnInputRequest,
    TurnReplyRequest,
)
from .workspace import (
    WorkspaceRestoreRequest,
    WorkspaceTrashRequest,
    WorkspaceWriteRequest,
)

__all__ = [
    "ConfigDeleteMutationRequest",
    "ConfigApplyRequest",
    "ConfigMutationRequest",
    "ConfigPatchRequest",
    "ConfigSetMutationRequest",
    "PresetCreateRequest",
    "PresetUpdateRequest",
    "ControlRequest",
    "InputRequest",
    "TurnCreateRequest",
    "TurnGrantRequest",
    "TurnInputRequest",
    "TurnReplyRequest",
    "ReflectionRequest",
    "WorkspaceRestoreRequest",
    "WorkspaceTrashRequest",
    "WorkspaceWriteRequest",
    "CommandReceiptResponse",
    "ActionCatalogResponse",
    "ConfigCatalogResponse",
    "ConfigMutationResponse",
    "ConfigResponse",
    "ContextMessagesResponse",
    "ContextOverviewResponse",
    "HealthResponse",
    "InteractionPageResponse",
    "JobDetailResponse",
    "JobListResponse",
    "JobOutputResponse",
    "PageResponse",
    "PresetListResponse",
    "PresetDeleteResponse",
    "PresetResponse",
    "ResourceResolveResponse",
    "RuntimeStatusResponse",
    "SearchResponse",
    "TurnResponse",
    "TurnListResponse",
]
