"""
Ask User Action - suspends the loop to ask the user a question.

The question is generated by Step 2a (framework LLM). This action has
llm_dependency=NONE because execute() does not call an internal LLM.
It emits LOOP_SUSPEND to pause the query loop.
"""
import json

from tinysoul.action.framework.executor import ActionExecutor
from tinysoul.action.framework.handler import ActionBase
from tinysoul.action.framework.run_config import RunConfig
from tinysoul.trap import ActionInputError
from tinysoul.trap.signal import Signal, SignalType
from tinysoul.context.protocols import ContextProvider

ACTION_SPEC_ASK_USER = {
    "name": "ask_user",
    "description": "Ask the user a clarifying question when the query is ambiguous, critical information is missing, or user confirmation is needed before a destructive action. This action SUSPENDS the loop and returns control to the user.",
    "cluster": {
        "type": "NATIVE",
        "domain": "BASIC",
    },
    "profile": {
        "action_intention": "EXTERNAL_PROBING",
        "action_environment_effect": "READ_ONLY",
        "action_mode": "SINGLE_RUN",
        "llm_dependency": "NONE",
    },
    "contract": {
        "applicability": {
            "mode": "CONDITIONAL",
            "conditions": [
                "user query is ambiguous or underspecified",
                "missing critical information needed to proceed",
                "need user confirmation before destructive operation",
                "need user to choose between alternatives",
            ],
        },
        "preconditions": [
            "The question must be clear and contextual",
            "Options, if provided, must be exhaustive and mutually exclusive",
        ],
        "postconditions": {
            "logical_state_effects": [
                "The query loop is SUSPENDED",
                "The question is recorded in query_events history",
                "Loop resumes when user provides an answer",
            ],
            "physical_environment_effects": [],
        },
    },
    "detail": {
        "parameter_schema": {
            "type": "object",
            "properties": {
                "question": {
                    "type": "string",
                    "description": "The question to ask the user. Must be clear, concise, and contextual.",
                },
                "context": {
                    "type": "string",
                    "description": "Brief explanation of WHY this question is being asked (1-2 sentences).",
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string",
                    },
                    "description": "Optional predefined options for the user to choose from.",
                },
                "urgency": {
                    "type": "string",
                    "enum": [
                        "blocking",
                        "optional",
                    ],
                    "description": "blocking = loop cannot proceed without answer; optional = answer would help but is not required",
                },
            },
            "required": [
                "question",
                "context",
            ],
        },
        "examples": [
            {
                "question": "What are the breeds of your two dogs?",
                "context": "I need the breeds to look up their average weights.",
                "options": [
                    "Border Collie + Scottish Terrier",
                    "Other (please specify)",
                ],
                "urgency": "blocking",
            },
        ],
        "edge_case_handling": [
            "User might provide an unexpected answer: the loop will handle it on resume",
            "Multiple ask_user actions in one turn: the first SUSPEND wins",
        ],
    },
}

ACTION_JSON_ASK_USER = json.dumps(ACTION_SPEC_ASK_USER, ensure_ascii=False, indent=2)


class AskUserExecutor(ActionExecutor):
    """Executor for ask_user action. No internal LLM call."""

    def execute(
        self,
        action_input: dict,
        context_provider: ContextProvider | None,
        run_config: RunConfig,
    ) -> dict:
        run_config.raise_if_terminated()
        question = action_input.get("question", "")
        context = action_input.get("context", "")
        options = action_input.get("options", [])
        urgency = action_input.get("urgency", "blocking")

        if not question:
            raise ActionInputError("question is required", action_input=action_input)
        if not context:
            raise ActionInputError("context is required", action_input=action_input)

        # Save the question to query_events history
        if context_provider is not None:
            context_provider.append_inquiry(question)

        result = {
            "question": question,
            "context": context,
            "options": options,
            "urgency": urgency,
        }

        # Emit LOOP_SUSPEND to pause the query loop.
        # Control flow signals carry NO data; action data travels via ACTION_COMPLETED.
        if context_provider is not None:
            context_provider.emit_signal(
                Signal(
                    type=SignalType.LOOP_SUSPEND,
                    turn=context_provider.current_turn,
                    step="execute_action",
                    action_name="ask_user",
                    action_input=action_input,
                    execution_id=run_config.execution_id,
                    payload={},
                )
            )

        return result


class AskUserAction(ActionBase):
    """Action to ask the user a question and suspend the loop."""

    action_name = "ask_user"
    ACTION_JSON = ACTION_JSON_ASK_USER
    _executor = AskUserExecutor()


def register_to(registry):
    """Register askuser action to the given registry."""
    from tinysoul.action.framework.registry import ActionRegistry

    if isinstance(registry, ActionRegistry):
        registry.register_action_class(AskUserAction)
